import Head from "next/head";
// import Image from "next/image";
// import dynamic from "next/dynamic";

// import styles from "../styles/Home.module.css";

import Header from "../../components/pages/Header";
import Post from "../../components/pages/Post";

import testPosts from "../../components/contents/post.json";

export default function HomeBlog({ post }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Post post={post[0]} />
    </div>
  );
}

export const getServerSideProps = async (context) => {
  //   console.log(context.params.id);
  const selectedPost = await testPosts.filter((post) => {
    if (post.id == context.params.id) return post;
  });

  // console.log(selectedPost);
  return {
    props: {
      post: selectedPost,
    },
  };
};
