import Head from "next/head";
// import Image from "next/image";
// import dynamic from "next/dynamic";

import styles from "../styles/Home.module.css";

import Header from "../components/pages/Header";
import MainBlog from "../components/pages/MainBlog";
// const MainBlog = dynamic(() => import("../components/pages/MainBlog"), {
// ssr: false,
// });

import testPosts from "../components/contents/post.json";

import { Swiper, SwiperSlide } from "swiper/react";

// // import Swiper core and required modules
// import SwiperCore, { Pagination } from "swiper/core";

// // install Swiper modules
// SwiperCore.use([Pagination]);

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <MainBlog posts={posts} title="Popular" />
      {/* <MainBlog posts={posts} title="Popular" /> */}
      {/* <MainBlog posts={posts} title="Newest" /> */}
    </div>
  );
}

export async function getStaticProps() {
  return {
    props: {
      posts: testPosts,
    },
  };
}
