import {useState} from 'react'
import Head from "next/head";
import dynamic from "next/dynamic";
// https://github.com/jpuri/react-draft-wysiwyg/issues/893
// https://github.com/jpuri/react-draft-wysiwyg/issues/893
// https://github.com/jpuri/react-draft-wysiwyg/issues/893
// https://github.com/jpuri/react-draft-wysiwyg/issues/893
// https://github.com/jpuri/react-draft-wysiwyg/issues/893

// import { Editor } from 'react-draft-wysiwyg';
import '../../node_modules/react-draft-wysiwyg/dist/react-draft-wysiwyg.css';

import Header from "../../components/pages/Header";

export default function AdminHome({ posts }) {

const Editor = dynamic(() => import('react-draft-wysiwyg').then(mod => mod.Editor));

const [dataEditor, setDataEditor] = useState();

const onEditorStateChange = (e, editorState) => {
    e.preventDefault();
    setDataEditor(editorState);
    console.log(dataEditor)
}
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Editor editorState={dataEditor} onEditorStateChange={onEditorStateChange} />

      <h1>Admin</h1>
      

    </div>
  );
}

export async function getStaticProps() {
  return {
    props: {
      posts: null,
    },
  };
}
